# Generated by Django 4.2.7 on 2024-12-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autologin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecredentials',
            name='login_button_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='websitecredentials',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='websitecredentials',
            name='password_field_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='websitecredentials',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='websitecredentials',
            name='username_field_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
